
exports.seed = function(knex, Promise) {

      return knex('songs').insert(
        [ { id: '9',
            name: 'Jet Blue Jet',
            spotify_song_id: '6tC8TvioT5048CG8qbd8WL',
            href: 'https://open.spotify.com/track/6tC8TvioT5048CG8qbd8WL',
            users_albums_id: '27' },
          { id: '10',
            name: 'Jah No Partial',
            spotify_song_id: '3Q4a9ApgFnZ9w12aowAZeD',
            href: 'https://open.spotify.com/track/3Q4a9ApgFnZ9w12aowAZeD',
            users_albums_id: '27' },
          { id: '11',
            name: 'Wind Up',
            spotify_song_id: '33z1fMV8v0x5ZhFakqQCXN',
            href: 'https://open.spotify.com/track/33z1fMV8v0x5ZhFakqQCXN',
            users_albums_id: '27' },
          { id: '12',
            name: 'Scare Me',
            spotify_song_id: '3v38IZ7dcfghTvxArU7qyc',
            href: 'https://open.spotify.com/track/3v38IZ7dcfghTvxArU7qyc',
            users_albums_id: '27' },
          { id: '13',
            name: 'All There Is (feat. Steffaloo)',
            spotify_song_id: '1SARbfnOIcuohWfh4pdLuC',
            href: 'https://open.spotify.com/track/1SARbfnOIcuohWfh4pdLuC',
            users_albums_id: '28' },
          { id: '14',
            name: '<3 & Soul',
            spotify_song_id: '65RMwvLBIXV2L9FWcF7xzZ',
            href: 'https://open.spotify.com/track/65RMwvLBIXV2L9FWcF7xzZ',
            users_albums_id: '28' },
          { id: '15',
            name: 'Soul & <3',
            spotify_song_id: '2QcIcaZF8dhG2iRxYWyD3M',
            href: 'https://open.spotify.com/track/2QcIcaZF8dhG2iRxYWyD3M',
            users_albums_id: '28' },
          { id: '16',
            name: 'Black Mambo',
            spotify_song_id: '63OC8cNa4ZnFB3bbvbWCOc',
            href: 'https://open.spotify.com/track/63OC8cNa4ZnFB3bbvbWCOc',
            users_albums_id: '29' },
          { id: '17',
            name: 'Pools',
            spotify_song_id: '7jO2B8Xgfu7D9vj60XiG7Y',
            href: 'https://open.spotify.com/track/7jO2B8Xgfu7D9vj60XiG7Y',
            users_albums_id: '29' },
          { id: '18',
            name: 'Gooey',
            spotify_song_id: '1gk3FhAV07q9Jg77UxnVjX',
            href: 'https://open.spotify.com/track/1gk3FhAV07q9Jg77UxnVjX',
            users_albums_id: '29' },
          { id: '19',
            name: 'All the Trees of the Field Will Clap Their Hands',
            spotify_song_id: '5OojmQ36TXkfL2JfoFJcaq',
            href: 'https://open.spotify.com/track/5OojmQ36TXkfL2JfoFJcaq',
            users_albums_id: '30' },
          { id: '20',
            name: 'To Be Alone With You',
            spotify_song_id: '3tchJ8gDgMdaSxpaLxlr1F',
            href: 'https://open.spotify.com/track/3tchJ8gDgMdaSxpaLxlr1F',
            users_albums_id: '30' },
          { id: '21',
            name: 'Abraham',
            spotify_song_id: '4YpfqCRwb3ttShlTNaB2jU',
            href: 'https://open.spotify.com/track/4YpfqCRwb3ttShlTNaB2jU',
            users_albums_id: '30' },
          { id: '22',
            name: 'We Won\'t Need Legs To Stand',
            spotify_song_id: '76xUGq9XKnRBlGchz0jFqU',
            href: 'https://open.spotify.com/track/76xUGq9XKnRBlGchz0jFqU',
            users_albums_id: '30' },
          { id: '23',
            name: 'Let It Happen',
            spotify_song_id: '2X485T9Z5Ly0xyaghN73ed',
            href: 'https://open.spotify.com/track/2X485T9Z5Ly0xyaghN73ed',
            users_albums_id: '31' },
          { id: '24',
            name: 'The Less I Know The Better',
            spotify_song_id: '6K4t31amVTZDgR3sKmwUJJ',
            href: 'https://open.spotify.com/track/6K4t31amVTZDgR3sKmwUJJ',
            users_albums_id: '31' },
          { id: '25',
            name: 'Yes I\'m Changing',
            spotify_song_id: '0xtIp0lgccN85GfGOekS5L',
            href: 'https://open.spotify.com/track/0xtIp0lgccN85GfGOekS5L',
            users_albums_id: '31' },
          { id: '26',
            name: 'Past Life',
            spotify_song_id: '4a9fW33mYR8LhXBOLUhbfF',
            href: 'https://open.spotify.com/track/4a9fW33mYR8LhXBOLUhbfF',
            users_albums_id: '31' },
          { id: '27',
            name: 'The Coolest',
            spotify_song_id: '1R6nmC4HUGOGSKU02Wqa0v',
            href: 'https://open.spotify.com/track/1R6nmC4HUGOGSKU02Wqa0v',
            users_albums_id: '32' },
          { id: '28',
            name: 'Streets On Fire',
            spotify_song_id: '1fNpOEgu770UrRTzeVsKZT',
            href: 'https://open.spotify.com/track/1fNpOEgu770UrRTzeVsKZT',
            users_albums_id: '32' },
          { id: '29',
            name: 'Hip-Hop Saved My Life (feat. Nikki Jean)',
            spotify_song_id: '6N3oYlfZ2RPdjMYdHCRmFS',
            href: 'https://open.spotify.com/track/6N3oYlfZ2RPdjMYdHCRmFS',
            users_albums_id: '32' },
          { id: '30',
            name: 'Little Weapon (feat. Bishop G and Nikki Jean)',
            spotify_song_id: '7sb2qiE0af4NggQPa5FkYY',
            href: 'https://open.spotify.com/track/7sb2qiE0af4NggQPa5FkYY',
            users_albums_id: '32' },
          { id: '31',
            name: 'Unbelievers',
            spotify_song_id: '7psPPGwhFzP3pyOcb3ivcT',
            href: 'https://open.spotify.com/track/7psPPGwhFzP3pyOcb3ivcT',
            users_albums_id: '33' },
          { id: '32',
            name: 'Everlasting Arms',
            spotify_song_id: '5WbmgRh4WP3dfmcrPUDY4O',
            href: 'https://open.spotify.com/track/5WbmgRh4WP3dfmcrPUDY4O',
            users_albums_id: '33' },
          { id: '33',
            name: 'Step',
            spotify_song_id: '78J9MBkAoqfvyeEpQKJDzD',
            href: 'https://open.spotify.com/track/78J9MBkAoqfvyeEpQKJDzD',
            users_albums_id: '33' },
          { id: '34',
            name: 'Finger Back',
            spotify_song_id: '5OLQo8LBsfh0LszlsyWlzL',
            href: 'https://open.spotify.com/track/5OLQo8LBsfh0LszlsyWlzL',
            users_albums_id: '33' },
          { id: '35',
            name: 'King of Carrot Flowers Pt. 1',
            spotify_song_id: '17Nowmq4iF2rkbd1rAe1Vt',
            href: 'https://open.spotify.com/track/17Nowmq4iF2rkbd1rAe1Vt',
            users_albums_id: '34' },
          { id: '36',
            name: 'In the Aeroplane Over the Sea',
            spotify_song_id: '4OciRObYGzPzlU40U7YRc8',
            href: 'https://open.spotify.com/track/4OciRObYGzPzlU40U7YRc8',
            users_albums_id: '34' },
          { id: '37',
            name: 'Holland, 1945',
            spotify_song_id: '4iwMhMvcTqukn1n3NVjb2N',
            href: 'https://open.spotify.com/track/4iwMhMvcTqukn1n3NVjb2N',
            users_albums_id: '34' },
          { id: '38',
            name: 'Apocalypse Dreams',
            spotify_song_id: '7qU7vhCPKhkDiJYGoboISc',
            href: 'https://open.spotify.com/track/7qU7vhCPKhkDiJYGoboISc',
            users_albums_id: '35' },
          { id: '39',
            name: 'Feels Like We Only Go Backwards',
            spotify_song_id: '0LtOwyZoSNZKJWHqjzADpW',
            href: 'https://open.spotify.com/track/0LtOwyZoSNZKJWHqjzADpW',
            users_albums_id: '35' },
          { id: '40',
            name: 'Elephant',
            spotify_song_id: '6qZjm61s6u8Ead9sWxCDro',
            href: 'https://open.spotify.com/track/6qZjm61s6u8Ead9sWxCDro',
            users_albums_id: '35' },
          { id: '41',
            name:
             'Nothing That Has Happened So Far Has Been Anything We Could Control',
            spotify_song_id: '33JMMgxQKL3zJsZeMNC3gR',
            href: 'https://open.spotify.com/track/33JMMgxQKL3zJsZeMNC3gR',
            users_albums_id: '35' },
          { id: '42',
            name: 'While I\'m Alive',
            spotify_song_id: '6wtcxwSJs82tpdeIoj93LF',
            href: 'https://open.spotify.com/track/6wtcxwSJs82tpdeIoj93LF',
            users_albums_id: '36' },
          { id: '43',
            name: 'Sazed',
            spotify_song_id: '4kBJ91CVm5cPDMqKa6f5LU',
            href: 'https://open.spotify.com/track/4kBJ91CVm5cPDMqKa6f5LU',
            users_albums_id: '36' },
          { id: '44',
            name: 'Beach Monster',
            spotify_song_id: '41NHuwdfkxpqsKuQjeIpVA',
            href: 'https://open.spotify.com/track/41NHuwdfkxpqsKuQjeIpVA',
            users_albums_id: '36' },
          { id: '45',
            name: 'Fortune\'s Fool',
            spotify_song_id: '4A71hQMnt3QI2pviVYL7hq',
            href: 'https://open.spotify.com/track/4A71hQMnt3QI2pviVYL7hq',
            users_albums_id: '36' },
          { id: '46',
            name: 'Atlantis',
            spotify_song_id: '0os8UEZdjDblS0sfKebhGS',
            href: 'https://open.spotify.com/track/0os8UEZdjDblS0sfKebhGS',
            users_albums_id: '36' },
          { id: '47',
            name: 'Birth In Reverse',
            spotify_song_id: '31WoNmfwgisR09Xo3siDjc',
            href: 'https://open.spotify.com/track/31WoNmfwgisR09Xo3siDjc',
            users_albums_id: '37' },
          { id: '48',
            name: 'Prince Johnny',
            spotify_song_id: '7hLWQTGBtKo4pBpJ9CaQo9',
            href: 'https://open.spotify.com/track/7hLWQTGBtKo4pBpJ9CaQo9',
            users_albums_id: '37' },
          { id: '49',
            name: 'Digital Witness',
            spotify_song_id: '5L16tlSHNt93RiiRiCc8ya',
            href: 'https://open.spotify.com/track/5L16tlSHNt93RiiRiCc8ya',
            users_albums_id: '37' },
          { id: '50',
            name: 'My Silver Lining',
            spotify_song_id: '5BkNCuxzzid0gz9sx3NNbX',
            href: 'https://open.spotify.com/track/5BkNCuxzzid0gz9sx3NNbX',
            users_albums_id: '38' },
          { id: '51',
            name: 'The Bell',
            spotify_song_id: '1ieLrWvgtrh1LSadJZAUwk',
            href: 'https://open.spotify.com/track/1ieLrWvgtrh1LSadJZAUwk',
            users_albums_id: '38' },
          { id: '52',
            name: 'Stay Gold',
            spotify_song_id: '1mqRT3LFIm4EEgfehauyOS',
            href: 'https://open.spotify.com/track/1mqRT3LFIm4EEgfehauyOS',
            users_albums_id: '38' },
          { id: '53',
            name: 'Fleeting One',
            spotify_song_id: '1g9I3LWB7UjBpHXdzlROyZ',
            href: 'https://open.spotify.com/track/1g9I3LWB7UjBpHXdzlROyZ',
            users_albums_id: '38' },
          { id: '54',
            name: 'Harmonium',
            spotify_song_id: '7tip9DwhHZ18cCj07aH6sZ',
            href: 'https://open.spotify.com/track/7tip9DwhHZ18cCj07aH6sZ',
            users_albums_id: '39' },
          { id: '55',
            name: 'Fantasies',
            spotify_song_id: '083PqLCrRr2TCvaVsl7s7p',
            href: 'https://open.spotify.com/track/083PqLCrRr2TCvaVsl7s7p',
            users_albums_id: '39' },
          { id: '56',
            name: 'Chicago x 12',
            spotify_song_id: '3dNrOxN4G71UBpbbQdvPFh',
            href: 'https://open.spotify.com/track/3dNrOxN4G71UBpbbQdvPFh',
            users_albums_id: '39' },
          { id: '57',
            name: 'Adlai Stevenson',
            spotify_song_id: '21CfgUS6tTM8zQ0ncHmAO3',
            href: 'https://open.spotify.com/track/21CfgUS6tTM8zQ0ncHmAO3',
            users_albums_id: '40' },
          { id: '58',
            name: 'Chicago (acoustic version)',
            spotify_song_id: '2WIx7xWSjoaARZLGqpxcQY',
            href: 'https://open.spotify.com/track/2WIx7xWSjoaARZLGqpxcQY',
            users_albums_id: '40' },
          { id: '59',
            name: 'The Henney Buggy Band',
            spotify_song_id: '0b8nVJDWvfDdCFrJhr5B9x',
            href: 'https://open.spotify.com/track/0b8nVJDWvfDdCFrJhr5B9x',
            users_albums_id: '40' },
          { id: '60',
            name:
             'The Mistress Witch from McClure (or, The Mind That Knows Itself)',
            spotify_song_id: '0g6B1zuMfnBH1hxeshOf4Y',
            href: 'https://open.spotify.com/track/0g6B1zuMfnBH1hxeshOf4Y',
            users_albums_id: '40' },
          { id: '61',
            name: 'No Man\'s Land',
            spotify_song_id: '3wh5k5KVDBeSXAv9jIDTdO',
            href: 'https://open.spotify.com/track/3wh5k5KVDBeSXAv9jIDTdO',
            users_albums_id: '40' },
          { id: '62',
            name: 'jealous of roses',
            spotify_song_id: '7cXF6ZVxPFfIaTuHkfit7U',
            href: 'https://open.spotify.com/track/7cXF6ZVxPFfIaTuHkfit7U',
            users_albums_id: '41' },
          { id: '63',
            name: 'lovers’ carvings',
            spotify_song_id: '3JeT6Xcv6MlEHHylk8SKQ1',
            href: 'https://open.spotify.com/track/3JeT6Xcv6MlEHHylk8SKQ1',
            users_albums_id: '41' },
          { id: '64',
            name: 'all the flowers',
            spotify_song_id: '7pDv4YeKNqH8zHYcnU8lRj',
            href: 'https://open.spotify.com/track/7pDv4YeKNqH8zHYcnU8lRj',
            users_albums_id: '41' },
          { id: '65',
            name: 's’vive',
            spotify_song_id: '22AYLXUQSqKx0pwwB7yCBJ',
            href: 'https://open.spotify.com/track/22AYLXUQSqKx0pwwB7yCBJ',
            users_albums_id: '41' },
          { id: '66',
            name: 'Helena Beat',
            spotify_song_id: '4VbDJMkAX3dWNBdn3KH6Wx',
            href: 'https://open.spotify.com/track/4VbDJMkAX3dWNBdn3KH6Wx',
            users_albums_id: '42' },
          { id: '67',
            name: 'Waste',
            spotify_song_id: '2UyWClHKt6fut3IpS2tJiR',
            href: 'https://open.spotify.com/track/2UyWClHKt6fut3IpS2tJiR',
            users_albums_id: '42' },
          { id: '68',
            name: 'Don\'t Stop (Color on the Walls)',
            spotify_song_id: '4HRa9ZWcmZ8JD7UySPu0wT',
            href: 'https://open.spotify.com/track/4HRa9ZWcmZ8JD7UySPu0wT',
            users_albums_id: '42' },
          { id: '69',
            name: 'Houdini',
            spotify_song_id: '5Fli1xRi01bvCjsZvKWro0',
            href: 'https://open.spotify.com/track/5Fli1xRi01bvCjsZvKWro0',
            users_albums_id: '42' },
          { id: '71',
            name: 'Shadow People',
            spotify_song_id: '209g8XrYu3ov4Wt4bRk2Yw',
            href: 'https://open.spotify.com/track/209g8XrYu3ov4Wt4bRk2Yw',
            users_albums_id: '43' },
          { id: '73',
            name: 'Unbearable Why',
            spotify_song_id: '0H6kfYCHqT2NeP2Pd0GuoG',
            href: 'https://open.spotify.com/track/0H6kfYCHqT2NeP2Pd0GuoG',
            users_albums_id: '43' },
          { id: '75',
            name: 'All Good Naysayers, Speak Up! Or Forever Hold Your Peace!',
            spotify_song_id: '0CQer159JE2DyFd9ZxPKJm',
            href: 'https://open.spotify.com/track/0CQer159JE2DyFd9ZxPKJm',
            users_albums_id: '44' },
          { id: '80',
            name: 'Too Afraid To Love You',
            spotify_song_id: '1comODdI862K7ei34XZRa4',
            href: 'https://open.spotify.com/track/1comODdI862K7ei34XZRa4',
            users_albums_id: '45' },
          { id: '83',
            name: 'Raincoat',
            spotify_song_id: '21w2VjNut2RpKJ2t3TnVmQ',
            href: 'https://open.spotify.com/track/21w2VjNut2RpKJ2t3TnVmQ',
            users_albums_id: '46' },
          { id: '88',
            name: 'The Day You Died',
            spotify_song_id: '3tj5523lMxVh6TjcAb1tdS',
            href: 'https://open.spotify.com/track/3tj5523lMxVh6TjcAb1tdS',
            users_albums_id: '47' },
          { id: '90',
            name: 'Amsterdam',
            spotify_song_id: '0MnVD7YNcPKiqayEUBDnve',
            href: 'https://open.spotify.com/track/0MnVD7YNcPKiqayEUBDnve',
            users_albums_id: '48' },
          { id: '97',
            name: 'Taro',
            spotify_song_id: '4tmwiN9YU7xMjh2hoqcVuI',
            href: 'https://open.spotify.com/track/4tmwiN9YU7xMjh2hoqcVuI',
            users_albums_id: '49' },
          { id: '98',
            name: 'Modern Man',
            spotify_song_id: '2EIEJ1zpvjpHuL6eWKGDZ8',
            href: 'https://open.spotify.com/track/2EIEJ1zpvjpHuL6eWKGDZ8',
            users_albums_id: '50' },
          { id: '100',
            name: 'Sprawl II (Mountains Beyond Mountains)',
            spotify_song_id: '0U0p8weaMIbIFMJ0CPlvHV',
            href: 'https://open.spotify.com/track/0U0p8weaMIbIFMJ0CPlvHV',
            users_albums_id: '50' },
          { id: '101',
            name: 'Battery Kinzie',
            spotify_song_id: '5d3aH9vQkli5MDoY4kq4ZM',
            href: 'https://open.spotify.com/track/5d3aH9vQkli5MDoY4kq4ZM',
            users_albums_id: '51' },
          { id: '103',
            name: 'The Michael Jordan of Drunk Driving',
            spotify_song_id: '1rRWgPkHvwGN5VIiqYIn9V',
            href: 'https://open.spotify.com/track/1rRWgPkHvwGN5VIiqYIn9V',
            users_albums_id: '52' },
          { id: '74',
            name: 'Jackie Wants a Black Eye',
            spotify_song_id: '27qG9sy9FaxB7sd3pRMAAO',
            href: 'https://open.spotify.com/track/27qG9sy9FaxB7sd3pRMAAO',
            users_albums_id: '43' },
          { id: '76',
            name: 'Tahquamenon Falls',
            spotify_song_id: '3mTN3qvh2iy7QesYwe1KJs',
            href: 'https://open.spotify.com/track/3mTN3qvh2iy7QesYwe1KJs',
            users_albums_id: '44' },
          { id: '79',
            name: 'The Only One',
            spotify_song_id: '3QHA3SBpz2SDEpI1HuMT0e',
            href: 'https://open.spotify.com/track/3QHA3SBpz2SDEpI1HuMT0e',
            users_albums_id: '45' },
          { id: '82',
            name: 'À tout à l\'heure',
            spotify_song_id: '0uy4LNxyL0QmtDveDaiGwo',
            href: 'https://open.spotify.com/track/0uy4LNxyL0QmtDveDaiGwo',
            users_albums_id: '46' },
          { id: '89',
            name: 'I Don’t Blame You',
            spotify_song_id: '6D2ZD1yIFU1c1R7GdHsrtD',
            href: 'https://open.spotify.com/track/6D2ZD1yIFU1c1R7GdHsrtD',
            users_albums_id: '47' },
          { id: '91',
            name: 'Let\'s Call It Off - Single Version',
            spotify_song_id: '2vSOngXgxrX0vzhtFLj2mw',
            href: 'https://open.spotify.com/track/2vSOngXgxrX0vzhtFLj2mw',
            users_albums_id: '48' },
          { id: '94',
            name: 'Something Good',
            spotify_song_id: '3xqxETvPg43KWP0HOGiOmu',
            href: 'https://open.spotify.com/track/3xqxETvPg43KWP0HOGiOmu',
            users_albums_id: '49' },
          { id: '81',
            name: 'Howlin\' For You',
            spotify_song_id: '0grFc6klR3hxoHLcgCYsF4',
            href: 'https://open.spotify.com/track/0grFc6klR3hxoHLcgCYsF4',
            users_albums_id: '45' },
          { id: '84',
            name: 'You',
            spotify_song_id: '470GRgn0wzQWq5EBTqEQ9R',
            href: 'https://open.spotify.com/track/470GRgn0wzQWq5EBTqEQ9R',
            users_albums_id: '46' },
          { id: '86',
            name: 'Fall In Love',
            spotify_song_id: '5imUTBF35uIoABlV9g9da2',
            href: 'https://open.spotify.com/track/5imUTBF35uIoABlV9g9da2',
            users_albums_id: '47' },
          { id: '93',
            name: 'The Chills',
            spotify_song_id: '51qfUWB1VBQSSKupsfdLrD',
            href: 'https://open.spotify.com/track/51qfUWB1VBQSSKupsfdLrD',
            users_albums_id: '48' },
          { id: '95',
            name: 'Fitzpleasure',
            spotify_song_id: '7DdXf9x75iEVCHWfoRwRuR',
            href: 'https://open.spotify.com/track/7DdXf9x75iEVCHWfoRwRuR',
            users_albums_id: '49' },
          { id: '99',
            name: 'We Used to Wait',
            spotify_song_id: '37EmPMVwdBaKs7UhJOkHUU',
            href: 'https://open.spotify.com/track/37EmPMVwdBaKs7UhJOkHUU',
            users_albums_id: '50' },
          { id: '102',
            name: 'Helplessness Blues',
            spotify_song_id: '4UkynNKM3QAFnYukL8Udi6',
            href: 'https://open.spotify.com/track/4UkynNKM3QAFnYukL8Udi6',
            users_albums_id: '51' },
          { id: '104',
            name: 'Fucc the Devil',
            spotify_song_id: '5LfEdPw4jxAOTo0KBZWYRK',
            href: 'https://open.spotify.com/track/5LfEdPw4jxAOTo0KBZWYRK',
            users_albums_id: '52' },
          { id: '105',
            name: 'If You Have Love in Your Heart',
            spotify_song_id: '4M2dOqJpPwzk0783soTQ3V',
            href: 'https://open.spotify.com/track/4M2dOqJpPwzk0783soTQ3V',
            users_albums_id: '52' },
          { id: '106',
            name: 'Sorry Bro',
            spotify_song_id: '274CtF0pVs3aYukfUHatcz',
            href: 'https://open.spotify.com/track/274CtF0pVs3aYukfUHatcz',
            users_albums_id: '52' },
          { id: '107',
            name: 'People II 2: Still Peoplin\'',
            spotify_song_id: '5AAoW30tLLLj1EziA439l4',
            href: 'https://open.spotify.com/track/5AAoW30tLLLj1EziA439l4',
            users_albums_id: '52' },
          { id: '108',
            name: 'The Golden Age',
            spotify_song_id: '1bGas968flWbyqIdVqlHt4',
            href: 'https://open.spotify.com/track/1bGas968flWbyqIdVqlHt4',
            users_albums_id: '53' },
          { id: '110',
            name: 'One Thing',
            spotify_song_id: '3Tk6n0bGkuVEtHWQ13tlgU',
            href: 'https://open.spotify.com/track/3Tk6n0bGkuVEtHWQ13tlgU',
            users_albums_id: '54' },
          { id: '112',
            name: 'Get On Your Knees',
            spotify_song_id: '3Cl3uNEcYu5SDhLLXN5yhi',
            href: 'https://open.spotify.com/track/3Cl3uNEcYu5SDhLLXN5yhi',
            users_albums_id: '55' },
          { id: '117',
            name: 'King of the World',
            spotify_song_id: '3QNVDWzBXxbwWcBwZc79qM',
            href: 'https://open.spotify.com/track/3QNVDWzBXxbwWcBwZc79qM',
            users_albums_id: '56' },
          { id: '119',
            name: 'Gunshot',
            spotify_song_id: '5mSjJvTv9l5X2CblEa2ehN',
            href: 'https://open.spotify.com/track/5mSjJvTv9l5X2CblEa2ehN',
            users_albums_id: '57' },
          { id: '121',
            name: 'Heaven Knows I\'m Miserable Now (2008 Remastered Version)',
            spotify_song_id: '0IAJt0QDTR2Jycq1Q010UR',
            href: 'https://open.spotify.com/track/0IAJt0QDTR2Jycq1Q010UR',
            users_albums_id: '58' },
          { id: '124',
            name: 'Girlfriend In A Coma (2008 Remastered Version)',
            spotify_song_id: '5UDKpn7nQb2v7pEPBWBB2t',
            href: 'https://open.spotify.com/track/5UDKpn7nQb2v7pEPBWBB2t',
            users_albums_id: '58' },
          { id: '126',
            name: 'Say Yeah',
            spotify_song_id: '4mt3KIwdthBHi1436xs3Gt',
            href: 'https://open.spotify.com/track/4mt3KIwdthBHi1436xs3Gt',
            users_albums_id: '59' },
          { id: '130',
            name: 'Never Ever',
            spotify_song_id: '6d4cLYfy0LmkxQZZaU2luP',
            href: 'https://open.spotify.com/track/6d4cLYfy0LmkxQZZaU2luP',
            users_albums_id: '60' },
           { id: '134',
            name: 'Can I Sit Next to You',
            spotify_song_id: '0AEDv1M9FMXJGFprzukZqy',
            href: 'https://open.spotify.com/track/0AEDv1M9FMXJGFprzukZqy',
            users_albums_id: '61' },
          { id: '136',
            name: 'Argentina (Parts I, II, III)',
            spotify_song_id: '0Gt0VoFADTKRK4gk9FkmfZ',
            href: 'https://open.spotify.com/track/0Gt0VoFADTKRK4gk9FkmfZ',
            users_albums_id: '62' },
          { id: '141',
            name: 'Swimming Pools (Drank) - Extended Version',
            spotify_song_id: '5ujh1I7NZH5agbwf7Hp8Hc',
            href: 'https://open.spotify.com/track/5ujh1I7NZH5agbwf7Hp8Hc',
            users_albums_id: '63' },
          { id: '145',
            name: 'Mustache Man (Wasted)',
            spotify_song_id: '5YfE7GXM5Mfs9Aul3uth1j',
            href: 'https://open.spotify.com/track/5YfE7GXM5Mfs9Aul3uth1j',
            users_albums_id: '64' },
          { id: '148',
            name: 'Play Tough',
            spotify_song_id: '7lVb2knw2VA7mgC75FQa4b',
            href: 'https://open.spotify.com/track/7lVb2knw2VA7mgC75FQa4b',
            users_albums_id: '65' },
          { id: '151',
            name: 'Should Have Taken Acid With You',
            spotify_song_id: '3EsVV4nHVVEJcEDiXIezUz',
            href: 'https://open.spotify.com/track/3EsVV4nHVVEJcEDiXIezUz',
            users_albums_id: '66' },
          { id: '154',
            name: 'The Glow',
            spotify_song_id: '73NGLYW9j5rbizafcDTvMG',
            href: 'https://open.spotify.com/track/73NGLYW9j5rbizafcDTvMG',
            users_albums_id: '67' },
          { id: '109',
            name: 'Majorette',
            spotify_song_id: '73guNXAOFu7XB6Sby4ahCp',
            href: 'https://open.spotify.com/track/73guNXAOFu7XB6Sby4ahCp',
            users_albums_id: '54' },
          { id: '111',
            name: 'All Your Yeahs',
            spotify_song_id: '1Q4jlbtXVPSwLZarmZohAI',
            href: 'https://open.spotify.com/track/1Q4jlbtXVPSwLZarmZohAI',
            users_albums_id: '54' },
          { id: '113',
            name: 'Anaconda',
            spotify_song_id: '4M7aciOBSbGnh1bN3YbuS0',
            href: 'https://open.spotify.com/track/4M7aciOBSbGnh1bN3YbuS0',
            users_albums_id: '55' },
          { id: '115',
            name: 'Emmylou',
            spotify_song_id: '3UzvFIyu5qdRepwJViDwjN',
            href: 'https://open.spotify.com/track/3UzvFIyu5qdRepwJViDwjN',
            users_albums_id: '56' },
          { id: '120',
            name: 'Never Gonna Love Again',
            spotify_song_id: '260P406V4ys84uDOFGfcMA',
            href: 'https://open.spotify.com/track/260P406V4ys84uDOFGfcMA',
            users_albums_id: '57' },
          { id: '122',
            name: 'Panic (2008 Remastered Version)',
            spotify_song_id: '3EqlxVkUnHPrQIAUnXTX1s',
            href: 'https://open.spotify.com/track/3EqlxVkUnHPrQIAUnXTX1s',
            users_albums_id: '58' },
          { id: '125',
            name: 'Hey Big Star',
            spotify_song_id: '26BJz4zDo0RdxmXFMXgsaZ',
            href: 'https://open.spotify.com/track/26BJz4zDo0RdxmXFMXgsaZ',
            users_albums_id: '59' },
          { id: '132',
            name: 'Open Your Eyes',
            spotify_song_id: '0xxm1WskKZSCvbkGjkSMr2',
            href: 'https://open.spotify.com/track/0xxm1WskKZSCvbkGjkSMr2',
            users_albums_id: '60' },
          { id: '135',
            name: 'First Caress',
            spotify_song_id: '5SuDHp0byZPcqLevynoiah',
            href: 'https://open.spotify.com/track/5SuDHp0byZPcqLevynoiah',
            users_albums_id: '61' },
          { id: '137',
            name: 'Beaches',
            spotify_song_id: '77et2LWxKJwxsJIZQsn8jN',
            href: 'https://open.spotify.com/track/77et2LWxKJwxsJIZQsn8jN',
            users_albums_id: '62' },
          { id: '139',
            name: 'Bitch, Don’t Kill My Vibe',
            spotify_song_id: '712uvW1Vezq8WpQi38v2L9',
            href: 'https://open.spotify.com/track/712uvW1Vezq8WpQi38v2L9',
            users_albums_id: '63' },
          { id: '146',
            name: 'Teenage Pregnancy',
            spotify_song_id: '5k91dz5DPBIKPkHFJc6evG',
            href: 'https://open.spotify.com/track/5k91dz5DPBIKPkHFJc6evG',
            users_albums_id: '64' },
          { id: '147',
            name: 'Same Old Drag',
            spotify_song_id: '4wXNHPynTETDmjElZOaomN',
            href: 'https://open.spotify.com/track/4wXNHPynTETDmjElZOaomN',
            users_albums_id: '65' },
          { id: '152',
            name: 'Psychic Chasms',
            spotify_song_id: '4xxng6eXixda7qkZIbdLF6',
            href: 'https://open.spotify.com/track/4xxng6eXixda7qkZIbdLF6',
            users_albums_id: '66' },
          { id: '156',
            name: 'Radio',
            spotify_song_id: '0idjTHGhGRBdWTmsalq3tF',
            href: 'https://open.spotify.com/track/0idjTHGhGRBdWTmsalq3tF',
            users_albums_id: '67' },
          { id: '158',
            name: 'We Are The People',
            spotify_song_id: '6fX7s3QNH9OWaISavemvcB',
            href: 'https://open.spotify.com/track/6fX7s3QNH9OWaISavemvcB',
            users_albums_id: '68' },
          { id: '159',
            name: 'We Were Rock & Roll',
            spotify_song_id: '4BDb93hwHyVwWbci7CzeDE',
            href: 'https://open.spotify.com/track/4BDb93hwHyVwWbci7CzeDE',
            users_albums_id: '69' },
          { id: '161',
            name: 'Look Into My Eyes',
            spotify_song_id: '7xWi0usCnICB2hkXkVwKeJ',
            href: 'https://open.spotify.com/track/7xWi0usCnICB2hkXkVwKeJ',
            users_albums_id: '69' },
          { id: '164',
            name: 'The Jean Genie - Single Mix [Remastered]',
            spotify_song_id: '6NO2kARLqr6DSJF3c7Pjbg',
            href: 'https://open.spotify.com/track/6NO2kARLqr6DSJF3c7Pjbg',
            users_albums_id: '70' },
          { id: '167',
            name: 'push pull',
            spotify_song_id: '6pTfJ82DLrBoTTaKJrFr7R',
            href: 'https://open.spotify.com/track/6pTfJ82DLrBoTTaKJrFr7R',
            users_albums_id: '71' },
          { id: '171',
            name: 'Haiti',
            spotify_song_id: '3Gkl2fJztF2B3fnUheejAA',
            href: 'https://open.spotify.com/track/3Gkl2fJztF2B3fnUheejAA',
            users_albums_id: '72' },
          { id: '114',
            name: 'Feeling Myself',
            spotify_song_id: '6ORDoQ6jxdfqNyqvUKDHF0',
            href: 'https://open.spotify.com/track/6ORDoQ6jxdfqNyqvUKDHF0',
            users_albums_id: '55' },
          { id: '116',
            name: 'Blue',
            spotify_song_id: '00wRLONfS2OOn3Jd8RwoIo',
            href: 'https://open.spotify.com/track/00wRLONfS2OOn3Jd8RwoIo',
            users_albums_id: '56' },
          { id: '118',
            name: 'Silver Line',
            spotify_song_id: '3Thvm2A6Vcaia8AE7ycZkI',
            href: 'https://open.spotify.com/track/3Thvm2A6Vcaia8AE7ycZkI',
            users_albums_id: '57' },
          { id: '123',
            name: 'Ask (2008 Remastered Version)',
            spotify_song_id: '0VAuJcy7fZulaEwXzTFiVP',
            href: 'https://open.spotify.com/track/0VAuJcy7fZulaEwXzTFiVP',
            users_albums_id: '58' },
          { id: '127',
            name: 'Can’t Let Go, Juno',
            spotify_song_id: '6A7ph3uhFzTUcUqOHE7NS7',
            href: 'https://open.spotify.com/track/6A7ph3uhFzTUcUqOHE7NS7',
            users_albums_id: '59' },
          { id: '129',
            name: 'Tape Machine',
            spotify_song_id: '3K4gWURajKtVQZk4NuQFWj',
            href: 'https://open.spotify.com/track/3K4gWURajKtVQZk4NuQFWj',
            users_albums_id: '60' },
          { id: '128',
            name: 'Who’d You Kill',
            spotify_song_id: '0PDE8rlHIPt4PmAigcwl3D',
            href: 'https://open.spotify.com/track/0PDE8rlHIPt4PmAigcwl3D',
            users_albums_id: '59' },
          { id: '131',
            name: 'Something Ain\'t Right',
            spotify_song_id: '1wIvB8FPi5egImEtmvLxSE',
            href: 'https://open.spotify.com/track/1wIvB8FPi5egImEtmvLxSE',
            users_albums_id: '60' },
          { id: '133',
            name: 'Hot Thoughts',
            spotify_song_id: '70x1x9NbSJJXkrgvIyyAVX',
            href: 'https://open.spotify.com/track/70x1x9NbSJJXkrgvIyyAVX',
            users_albums_id: '61' },
          { id: '138',
            name: 'Hot Tonight',
            spotify_song_id: '43peWAhiyf1D6TggXIzMJX',
            href: 'https://open.spotify.com/track/43peWAhiyf1D6TggXIzMJX',
            users_albums_id: '62' },
          { id: '140',
            name: 'Money Trees',
            spotify_song_id: '0AOvNRgl0SMfOibWA5bP8o',
            href: 'https://open.spotify.com/track/0AOvNRgl0SMfOibWA5bP8o',
            users_albums_id: '63' },
          { id: '143',
            name: 'Federal Funding',
            spotify_song_id: '4JJClLLXLAKLjjEGdglHZA',
            href: 'https://open.spotify.com/track/4JJClLLXLAKLjjEGdglHZA',
            users_albums_id: '64' },
          { id: '142',
            name: 'The Recipe - Bonus Track',
            spotify_song_id: '1eRBW1HcyM1zPlxO26cScZ',
            href: 'https://open.spotify.com/track/1eRBW1HcyM1zPlxO26cScZ',
            users_albums_id: '63' },
          { id: '144',
            name: 'Long Time',
            spotify_song_id: '3uK81IbKrK2xfLcjjCJDEE',
            href: 'https://open.spotify.com/track/3uK81IbKrK2xfLcjjCJDEE',
            users_albums_id: '64' },
          { id: '149',
            name: 'Sunndal Song',
            spotify_song_id: '2sSA7kCFK3YeDtAYGMQ0ad',
            href: 'https://open.spotify.com/track/2sSA7kCFK3YeDtAYGMQ0ad',
            users_albums_id: '65' },
          { id: '150',
            name: 'Laughing Gas',
            spotify_song_id: '5XhACsKjolP8pjPPgPT1zW',
            href: 'https://open.spotify.com/track/5XhACsKjolP8pjPPgPT1zW',
            users_albums_id: '66' },
          { id: '153',
            name: 'Local Joke',
            spotify_song_id: '53dCTXFhnemB8zP38UgQBr',
            href: 'https://open.spotify.com/track/53dCTXFhnemB8zP38UgQBr',
            users_albums_id: '66' },
          { id: '155',
            name: 'Just Dancing',
            spotify_song_id: '660w8RvCS8lOwl5r2GcJ0A',
            href: 'https://open.spotify.com/track/660w8RvCS8lOwl5r2GcJ0A',
            users_albums_id: '67' },
          { id: '157',
            name: 'Standing On The Shore',
            spotify_song_id: '7wME8torEQ606m3fj2XERm',
            href: 'https://open.spotify.com/track/7wME8torEQ606m3fj2XERm',
            users_albums_id: '68' },
          { id: '160',
            name: 'Dance Apocalyptic',
            spotify_song_id: '3dUMuxNadGxCE3qXuhCwqa',
            href: 'https://open.spotify.com/track/3dUMuxNadGxCE3qXuhCwqa',
            users_albums_id: '69' },
          { id: '165',
            name: 'Changes - Remastered',
            spotify_song_id: '4ttsQLMYKn1ZGYYeUdcyL4',
            href: 'https://open.spotify.com/track/4ttsQLMYKn1ZGYYeUdcyL4',
            users_albums_id: '70' },
          { id: '166',
            name: 'bodyache',
            spotify_song_id: '2DopRU3QWz4CWymUUrKvO4',
            href: 'https://open.spotify.com/track/2DopRU3QWz4CWymUUrKvO4',
            users_albums_id: '71' },
          { id: '169',
            name: 'Neighborhood #1 (Tunnels)',
            spotify_song_id: '0WZZJ0mDKIkLfL0710ssZt',
            href: 'https://open.spotify.com/track/0WZZJ0mDKIkLfL0710ssZt',
            users_albums_id: '72' },
          { id: '162',
            name: 'What An Experience',
            spotify_song_id: '4C1rkqM76nR6xmM6FGtmk3',
            href: 'https://open.spotify.com/track/4C1rkqM76nR6xmM6FGtmk3',
            users_albums_id: '69' },
          { id: '163',
            name: 'Life On Mars? - 2016 Mix',
            spotify_song_id: '5URyZdvvKmroIvKygewKJF',
            href: 'https://open.spotify.com/track/5URyZdvvKmroIvKygewKJF',
            users_albums_id: '70' },
          { id: '168',
            name: 'repetition',
            spotify_song_id: '0rKaBFkllvlD2fdhJvpqPt',
            href: 'https://open.spotify.com/track/0rKaBFkllvlD2fdhJvpqPt',
            users_albums_id: '71' },
          { id: '170',
            name: 'Rebellion (Lies)',
            spotify_song_id: '0xOeB16JDbBJBJKSdHbElT',
            href: 'https://open.spotify.com/track/0xOeB16JDbBJBJKSdHbElT',
            users_albums_id: '72' },
          { id: '172',
            name: 'Normal Person',
            spotify_song_id: '3KMhWFbexTo20tH3hwK61K',
            href: 'https://open.spotify.com/track/3KMhWFbexTo20tH3hwK61K',
            users_albums_id: '74' },
          { id: '173',
            name: 'Here Comes The Night Time II',
            spotify_song_id: '7zIgrNq7doluy1dMdTli3u',
            href: 'https://open.spotify.com/track/7zIgrNq7doluy1dMdTli3u',
            users_albums_id: '74' },
          { id: '177',
            name: 'Ragged Wood',
            spotify_song_id: '0DrPfPbgV3TxsxgqEjQzPk',
            href: 'https://open.spotify.com/track/0DrPfPbgV3TxsxgqEjQzPk',
            users_albums_id: '75' },
          { id: '174',
            name: 'Joan Of Arc',
            spotify_song_id: '2vM2x66y8JcDARNarbrw9F',
            href: 'https://open.spotify.com/track/2vM2x66y8JcDARNarbrw9F',
            users_albums_id: '74' },
          { id: '179',
            name: 'He Doesn\'t Know Why',
            spotify_song_id: '0g4PeGxMoI44u5VGfhhNud',
            href: 'https://open.spotify.com/track/0g4PeGxMoI44u5VGfhhNud',
            users_albums_id: '75' },
          { id: '182',
            name: 'Ocean of Noise',
            spotify_song_id: '1ocL0Mdp2NKggF7kG3Qdm2',
            href: 'https://open.spotify.com/track/1ocL0Mdp2NKggF7kG3Qdm2',
            users_albums_id: '76' },
          { id: '185',
            name: 'Up From Below',
            spotify_song_id: '5yDkwJfbUaswNHCFGlgwJO',
            href: 'https://open.spotify.com/track/5yDkwJfbUaswNHCFGlgwJO',
            users_albums_id: '77' },
          { id: '187',
            name: 'oh baby',
            spotify_song_id: '53PkA8aXiwH4ppa0V0iO7o',
            href: 'https://open.spotify.com/track/53PkA8aXiwH4ppa0V0iO7o',
            users_albums_id: '78' },
          { id: '190',
            name: 'american dream',
            spotify_song_id: '60k0xRw1oYUwZYp4e2iue8',
            href: 'https://open.spotify.com/track/60k0xRw1oYUwZYp4e2iue8',
            users_albums_id: '78' },
          { id: '192',
            name: 'Hypothetical',
            spotify_song_id: '5oy1V08wGzZIXPizaWO6Kh',
            href: 'https://open.spotify.com/track/5oy1V08wGzZIXPizaWO6Kh',
            users_albums_id: '79' },
          { id: '195',
            name: 'Petals',
            spotify_song_id: '1TVd8FHpeg1Afa92kaO0kR',
            href: 'https://open.spotify.com/track/1TVd8FHpeg1Afa92kaO0kR',
            users_albums_id: '80' },
          { id: '198',
            name: 'Light Up The Sky',
            spotify_song_id: '70ezCCwti8PBRFX0Z7FztA',
            href: 'https://open.spotify.com/track/70ezCCwti8PBRFX0Z7FztA',
            users_albums_id: '80' },
          { id: '199',
            name: 'Pills',
            spotify_song_id: '6jcKQzA6fxIrof4AlrojG1',
            href: 'https://open.spotify.com/track/6jcKQzA6fxIrof4AlrojG1',
            users_albums_id: '81' },
          { id: '201',
            name: 'Pretentious',
            spotify_song_id: '3Q5fvTZlPnu2M61cbTbE5y',
            href: 'https://open.spotify.com/track/3Q5fvTZlPnu2M61cbTbE5y',
            users_albums_id: '82' },
          { id: '205',
            name: 'Electric Blue',
            spotify_song_id: '0KWcRXcnGoB0gWSu4mshF8',
            href: 'https://open.spotify.com/track/0KWcRXcnGoB0gWSu4mshF8',
            users_albums_id: '83' },
          { id: '209',
            name: 'Hit Me Like That Snare',
            spotify_song_id: '65bDyccq2aZSdT2woykFkw',
            href: 'https://open.spotify.com/track/65bDyccq2aZSdT2woykFkw',
            users_albums_id: '84' },
          { id: '211',
            name: 'Unforgettable Season',
            spotify_song_id: '4FNTkYnZxw8So7mSmkUZIa',
            href: 'https://open.spotify.com/track/4FNTkYnZxw8So7mSmkUZIa',
            users_albums_id: '85' },
          { id: '214',
            name: 'Far Away',
            spotify_song_id: '7inY9S6RNeDsUNd5zbDGQL',
            href: 'https://open.spotify.com/track/7inY9S6RNeDsUNd5zbDGQL',
            users_albums_id: '85' },
          { id: '216',
            name: 'Good As Hell',
            spotify_song_id: '043CB5VqGkGOXOCndP650N',
            href: 'https://open.spotify.com/track/043CB5VqGkGOXOCndP650N',
            users_albums_id: '86' },
          { id: '218',
            name: 'Earth',
            spotify_song_id: '7JVUV09TJbGJfE8lfBpWlY',
            href: 'https://open.spotify.com/track/7JVUV09TJbGJfE8lfBpWlY',
            users_albums_id: '87' },
          { id: '175',
            name: 'It’s Never Over (Hey Orpheus)',
            spotify_song_id: '0MWnFXte9zokisZDWZG0gR',
            href: 'https://open.spotify.com/track/0MWnFXte9zokisZDWZG0gR',
            users_albums_id: '74' },
          { id: '180',
            name: 'Blue Ridge Mountains',
            spotify_song_id: '03CMUlyOZzrNXJnb8Vzm4l',
            href: 'https://open.spotify.com/track/03CMUlyOZzrNXJnb8Vzm4l',
            users_albums_id: '75' },
          { id: '181',
            name: 'Intervention',
            spotify_song_id: '7Bl5Fqa2g1UFs2O1VJiKhb',
            href: 'https://open.spotify.com/track/7Bl5Fqa2g1UFs2O1VJiKhb',
            users_albums_id: '76' },
          { id: '186',
            name: 'Om Nashi Me',
            spotify_song_id: '5lYAfqEeShMx0q4TQXeO1Z',
            href: 'https://open.spotify.com/track/5lYAfqEeShMx0q4TQXeO1Z',
            users_albums_id: '77' },
          { id: '188',
            name: 'call the police',
            spotify_song_id: '51vOZQuGnqPXfU5VbTZqZb',
            href: 'https://open.spotify.com/track/51vOZQuGnqPXfU5VbTZqZb',
            users_albums_id: '78' },
          { id: '193',
            name: 'Philip the Engineer',
            spotify_song_id: '2FNhAkbg84o1bfBVUo6XCu',
            href: 'https://open.spotify.com/track/2FNhAkbg84o1bfBVUo6XCu',
            users_albums_id: '79' },
          { id: '197',
            name: 'Why So Serious?',
            spotify_song_id: '4BJzKdCz0zMnqITMESu3b5',
            href: 'https://open.spotify.com/track/4BJzKdCz0zMnqITMESu3b5',
            users_albums_id: '80' },
          { id: '200',
            name: 'Savior',
            spotify_song_id: '0uXOXjd0iaptu1co1BJrif',
            href: 'https://open.spotify.com/track/0uXOXjd0iaptu1co1BJrif',
            users_albums_id: '81' },
          { id: '202',
            name: 'K is for Kelson',
            spotify_song_id: '0N9RS57N5KlT2aWM3UmhV7',
            href: 'https://open.spotify.com/track/0N9RS57N5KlT2aWM3UmhV7',
            users_albums_id: '82' },
          { id: '206',
            name: 'Creature Comfort',
            spotify_song_id: '2voWPWlDfIthC6GUjaIQyV',
            href: 'https://open.spotify.com/track/2voWPWlDfIthC6GUjaIQyV',
            users_albums_id: '83' },
          { id: '208',
            name: 'In Cold Blood',
            spotify_song_id: '0jeJR3LdrC2QJNviq7wjzp',
            href: 'https://open.spotify.com/track/0jeJR3LdrC2QJNviq7wjzp',
            users_albums_id: '84' },
          { id: '213',
            name: 'So Haunted',
            spotify_song_id: '63MaRhpygmnQk38HQU1gse',
            href: 'https://open.spotify.com/track/63MaRhpygmnQk38HQU1gse',
            users_albums_id: '85' },
          { id: '215',
            name: 'Scuse Me',
            spotify_song_id: '26Q7f4tUntDtlL4EyZz65X',
            href: 'https://open.spotify.com/track/26Q7f4tUntDtlL4EyZz65X',
            users_albums_id: '86' },
          { id: '217',
            name: 'Jupiter',
            spotify_song_id: '18nqBWakhV4TUThL08m0iV',
            href: 'https://open.spotify.com/track/18nqBWakhV4TUThL08m0iV',
            users_albums_id: '87' },
          { id: '176',
            name: 'Porno',
            spotify_song_id: '4ld9QYEpwDD3m8gGfUn19Z',
            href: 'https://open.spotify.com/track/4ld9QYEpwDD3m8gGfUn19Z',
            users_albums_id: '74' },
          { id: '178',
            name: 'Tiger Mountain Peasant Song',
            spotify_song_id: '1YZBmsCYf8gKSCwYKu6l5U',
        
      
        href: 'https://open.spotify.com/track/1YZBmsCYf8gKSCwYKu6l5U',
        users_albums_id: '75' },
      { id: '183',
        name: 'Windowsill',
        spotify_song_id: '2XP4rhtpHlzJRUNhsD7eU3',
        href: 'https://open.spotify.com/track/2XP4rhtpHlzJRUNhsD7eU3',
        users_albums_id: '76' },
      { id: '184',
        name: '40 Day Dream',
        spotify_song_id: '12WtkO5DLE2CWjRGeXtwEW',
        href: 'https://open.spotify.com/track/12WtkO5DLE2CWjRGeXtwEW',
        users_albums_id: '77' },
      { id: '189',
        name: 'i used to',
        spotify_song_id: '5LQVkIyf3HwZ9i6Xk1i59H',
        href: 'https://open.spotify.com/track/5LQVkIyf3HwZ9i6Xk1i59H',
        users_albums_id: '78' },
      { id: '191',
        name: 'Gone',
        spotify_song_id: '3mxMrdo3fJjDbb64nagoXR',
        href: 'https://open.spotify.com/track/3mxMrdo3fJjDbb64nagoXR',
        users_albums_id: '79' },
      { id: '194',
        name: 'Break My Fall',
        spotify_song_id: '1UlSQTGmZlo4JcI6gk5x0H',
        href: 'https://open.spotify.com/track/1UlSQTGmZlo4JcI6gk5x0H',
        users_albums_id: '79' },
      { id: '196',
        name: 'Town & Country',
        spotify_song_id: '1nO357XsHkXI63l6Sn2dJd',
        href: 'https://open.spotify.com/track/1nO357XsHkXI63l6Sn2dJd',
        users_albums_id: '80' },
      { id: '203',
        name: 'Anything New',
        spotify_song_id: '3gEtuTSd1K4XfSp2ZoQG44',
        href: 'https://open.spotify.com/track/3gEtuTSd1K4XfSp2ZoQG44',
        users_albums_id: '82' },
      { id: '204',
        name: 'Everything Now',
        spotify_song_id: '7KsZHCfOitA5V9oQYVdltG',
        href: 'https://open.spotify.com/track/7KsZHCfOitA5V9oQYVdltG',
        users_albums_id: '83' },
      { id: '207',
        name: 'Good God Damn',
        spotify_song_id: '2ZssXuZfktUr4MMDzEWD2Z',
        href: 'https://open.spotify.com/track/2ZssXuZfktUr4MMDzEWD2Z',
        users_albums_id: '83' },
      { id: '210',
        name: 'Deadcrush',
        spotify_song_id: '7gn0MfkV4ZuMkqbPlmhIlx',
        href: 'https://open.spotify.com/track/7gn0MfkV4ZuMkqbPlmhIlx',
        users_albums_id: '84' },
      { id: '212',
        name: 'Hearts On Fire',
        spotify_song_id: '0pAisVoZ7Gybjvm0q7AoVu',
        href: 'https://open.spotify.com/track/0pAisVoZ7Gybjvm0q7AoVu',
        users_albums_id: '85' },
      { id: '219',
        name: 'Saturn',
        spotify_song_id: '65D8ZQMDOWCFNbPGZ55plY',
        href: 'https://open.spotify.com/track/65D8ZQMDOWCFNbPGZ55plY',
        users_albums_id: '87' },
      { id: '70',
        name: 'Miss You',
        spotify_song_id: '2aCsRmHTuWPL7WnL5uSijc',
        href: 'https://open.spotify.com/track/2aCsRmHTuWPL7WnL5uSijc',
        users_albums_id: '42' },
      { id: '72',
        name: 'Where\'d All the Time Go?',
        spotify_song_id: '0UV5zxRMz6AO4ZwUOZNIKI',
        href: 'https://open.spotify.com/track/0UV5zxRMz6AO4ZwUOZNIKI',
        users_albums_id: '43' },
      { id: '77',
        name: 'Say Yes! to M!ch!gan!',
        spotify_song_id: '5N9aJzWu56RVMfJ7wl4gBm',
        href: 'https://open.spotify.com/track/5N9aJzWu56RVMfJ7wl4gBm',
        users_albums_id: '44' },
      { id: '78',
        name: 'Next Girl',
        spotify_song_id: '2UE4m8egf0aREmOi47sDOk',
        href: 'https://open.spotify.com/track/2UE4m8egf0aREmOi47sDOk',
        users_albums_id: '45' },
      { id: '85',
        name: 'You Won\'t Remember...',
        spotify_song_id: '7DZIXHoj13Dwe0ys58zcyP',
        href: 'https://open.spotify.com/track/7DZIXHoj13Dwe0ys58zcyP',
        users_albums_id: '46' },
      { id: '87',
        name: 'Howling At The Moon',
        spotify_song_id: '00RYw42tKwXecTaVay3BKl',
        href: 'https://open.spotify.com/track/00RYw42tKwXecTaVay3BKl',
        users_albums_id: '47' },
      { id: '92',
        name: 'Up Against The Wall',
        spotify_song_id: '0oPOyY3KH2Vh6RE9iaRBsU',
        href: 'https://open.spotify.com/track/0oPOyY3KH2Vh6RE9iaRBsU',
        users_albums_id: '48' },
      { id: '96',
        name: 'Dissolve Me',
        spotify_song_id: '2Dv7PTwSoB17f3VFDIKw8m',
        href: 'https://open.spotify.com/track/2Dv7PTwSoB17f3VFDIKw8m',
        users_albums_id: '49' } 
        ])
        .then(() => {
          return knex.raw(`SELECT setval('songs_id_seq', (SELECT MAX(id) FROM songs));`)
        })
      };
